# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=4.0.26-0
maven_group=me.drex.fafpatch
archives_base_name=friends-and-foes-patch


# Dependencies
fabric_version=0.153.0+26.2
polymer_version=0.17.0+26.2-rc-2
factorytools_version=0.11.0+26.2
friends_and_foes_version=fabric-4.0.26+mc26.2
resourcefullib_version=resourcefullib-fabric-26.2:5.0.0
yacl_version=3.9.4+26.2-fabric